also provide useful test output when there is no expected_result file

diff --git a/regression-tests/runtests b/regression-tests/runtests
--- a/regression-tests/runtests
+++ b/regression-tests/runtests
@@ -55,7 +55,12 @@ do
 			[ -e "$a/expected_result.$extracontext" ] && expected=$a/expected_result.$extracontext
 		done
 		[ -n "$context" ] && [ -e "$a/expected_result.$context" ] && expected=$a/expected_result.$context
-		diff -u $expected $a/real_result > $a/diff
+		diff -u $expected $a/real_result > $a/diff 2>&1
+		if [ $? -gt 0 ]
+		then
+			echo "diff failed, full result follows" >> $a/diff
+			cat $a/real_result >> $a/diff
+		fi
 		if [ -s $a/diff ] 
 		then
 			result="	Failed test $a"
